#! /usr/bin/env perl
# Part of the culibs project, <http://www.eideticdew.org/culibs/>.
# Copyright (C) 2008  Petter Urkedal <urkedal@nbi.dk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use Getopt::Long;

my $out_path;
GetOptions('o=s' => \$out_path) and $out_path or die "Bad usage";

my @attrdefs;
while (<>) {
    if (/^#define cufoA_(\w+)\b.*\bCUFO_ATTR_(CSTR|INT)\b/) {
	my $name = $1;
	my $type = lc($2);
	push(@attrdefs, [$name, $type]);
    }
}

open O, '>', $out_path or die $!;
print O "/* This file is generated by $0. */\n\n";
print O "#include <cufo/attrdefs.h>\n";
print O "#include <cufo/tag.h>\n\n";
foreach my $attrdef (@attrdefs) {
    my ($name, $type) = @$attrdef;
    print O "struct cufo_attr_s cufoP_attr_${name};\n";
}
print O "\nvoid\ncufoP_attrdefs_init(void)\n{\n";
print O "\tcufo_namespace_t ns = cufo_culibs_namespace();\n";
foreach my $attrdef (@attrdefs) {
    my ($name, $type) = @$attrdef;
    my $xml_name = $name; $xml_name =~ tr/_/-/;
    print O "\tcufo_attr_init(\&cufoP_attr_${name}, ns, \"${xml_name}\", "
	   ."cufo_attrtype_$type);\n";
}
print O "}\n";
