/* Part of the culibs project, <http://www.eideticdew.org/culibs/>.
 * Copyright (C) 2007  Petter Urkedal <urkedal@nbi.dk>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* These are potential configuration macros, which at the moment are
 * hard-wired.  They may be moved to conf_ac.h (generated by configure.ac), as
 * needed.
 *
 * Normally this is included though conf.h, though some internal sources
 * includes it directly to avoid unnecessary recompilation.  */

#ifndef CU_CONF_FIXED_H
#define CU_CONF_FIXED_H

/* A value of AO_t which is guaranteed not to be a valid function pointer. */
#define CUCONF_AO_NOT_A_FUNCTION ((AO_t)-1)

#endif
